/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as ApiManagementRouteImport } from './routes/api-management'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StatsUsersRouteImport } from './routes/stats/users'
import { Route as StatsSystemRouteImport } from './routes/stats/system'
import { Route as StatsSessionsRouteImport } from './routes/stats/sessions'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password/$token'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminSchedulesRouteImport } from './routes/admin/schedules'
import { Route as AdminRateLimitsRouteImport } from './routes/admin/rate-limits'
import { Route as AdminOntologyRouteImport } from './routes/admin/ontology'
import { Route as AdminNewRouteImport } from './routes/admin/new'
import { Route as AdminNavigationRouteImport } from './routes/admin/navigation'
import { Route as AdminFirefighterRouteImport } from './routes/admin/firefighter'
import { Route as AdminDiscoveryRouteImport } from './routes/admin/discovery'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as AdminAccessRouteImport } from './routes/admin/access'
import { Route as AdminAbacRouteImport } from './routes/admin/abac'
import { Route as AdminOntologyIndexRouteImport } from './routes/admin/ontology/index'
import { Route as AdminDiscoveryIndexRouteImport } from './routes/admin/discovery/index'
import { Route as AdminRolesManagerRouteImport } from './routes/admin/roles/manager'
import { Route as AdminRolesDesignerRouteImport } from './routes/admin/roles/designer'
import { Route as AdminRolesDelegationRouteImport } from './routes/admin/roles/delegation'
import { Route as AdminOntologyVersionsRouteImport } from './routes/admin/ontology/versions'
import { Route as AdminOntologyDesignerRouteImport } from './routes/admin/ontology/designer'
import { Route as AdminOntologyContextsRouteImport } from './routes/admin/ontology/contexts'
import { Route as AdminOntologyRelationshipsRouteImport } from './routes/admin/ontology/Relationships'
import { Route as AdminOntologyGraphRouteImport } from './routes/admin/ontology/Graph'
import { Route as AdminOntologyClassesRouteImport } from './routes/admin/ontology/Classes'
import { Route as AdminDiscoveryServiceIdRouteImport } from './routes/admin/discovery/$serviceId'
import { Route as AdminAccessPoliciesRouteImport } from './routes/admin/access/policies'
import { Route as AdminAccessImpactRouteImport } from './routes/admin/access/impact'
import { Route as AdminAccessExplorerRouteImport } from './routes/admin/access/explorer'
import { Route as AdminAccessRolesRouteImport } from './routes/admin/access/Roles'
import { Route as AdminAccessPermissionsRouteImport } from './routes/admin/access/Permissions'
import { Route as AdminAccessMatrixRouteImport } from './routes/admin/access/Matrix'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManagementRoute = ApiManagementRouteImport.update({
  id: '/api-management',
  path: '/api-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StatsUsersRoute = StatsUsersRouteImport.update({
  id: '/stats/users',
  path: '/stats/users',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSystemRoute = StatsSystemRouteImport.update({
  id: '/stats/system',
  path: '/stats/system',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsSessionsRoute = StatsSessionsRouteImport.update({
  id: '/stats/sessions',
  path: '/stats/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRateLimitsRoute = AdminRateLimitsRouteImport.update({
  id: '/rate-limits',
  path: '/rate-limits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOntologyRoute = AdminOntologyRouteImport.update({
  id: '/ontology',
  path: '/ontology',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirefighterRoute = AdminFirefighterRouteImport.update({
  id: '/firefighter',
  path: '/firefighter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscoveryRoute = AdminDiscoveryRouteImport.update({
  id: '/discovery',
  path: '/discovery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccessRoute = AdminAccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAbacRoute = AdminAbacRouteImport.update({
  id: '/abac',
  path: '/abac',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOntologyIndexRoute = AdminOntologyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOntologyRoute,
} as any)
const AdminDiscoveryIndexRoute = AdminDiscoveryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDiscoveryRoute,
} as any)
const AdminRolesManagerRoute = AdminRolesManagerRouteImport.update({
  id: '/roles/manager',
  path: '/roles/manager',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesDesignerRoute = AdminRolesDesignerRouteImport.update({
  id: '/roles/designer',
  path: '/roles/designer',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesDelegationRoute = AdminRolesDelegationRouteImport.update({
  id: '/roles/delegation',
  path: '/roles/delegation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOntologyVersionsRoute = AdminOntologyVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AdminOntologyRoute,
} as any)
const AdminOntologyDesignerRoute = AdminOntologyDesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => AdminOntologyRoute,
} as any)
const AdminOntologyContextsRoute = AdminOntologyContextsRouteImport.update({
  id: '/contexts',
  path: '/contexts',
  getParentRoute: () => AdminOntologyRoute,
} as any)
const AdminOntologyRelationshipsRoute =
  AdminOntologyRelationshipsRouteImport.update({
    id: '/Relationships',
    path: '/Relationships',
    getParentRoute: () => AdminOntologyRoute,
  } as any)
const AdminOntologyGraphRoute = AdminOntologyGraphRouteImport.update({
  id: '/Graph',
  path: '/Graph',
  getParentRoute: () => AdminOntologyRoute,
} as any)
const AdminOntologyClassesRoute = AdminOntologyClassesRouteImport.update({
  id: '/Classes',
  path: '/Classes',
  getParentRoute: () => AdminOntologyRoute,
} as any)
const AdminDiscoveryServiceIdRoute = AdminDiscoveryServiceIdRouteImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => AdminDiscoveryRoute,
} as any)
const AdminAccessPoliciesRoute = AdminAccessPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessImpactRoute = AdminAccessImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessExplorerRoute = AdminAccessExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessRolesRoute = AdminAccessRolesRouteImport.update({
  id: '/Roles',
  path: '/Roles',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessPermissionsRoute = AdminAccessPermissionsRouteImport.update({
  id: '/Permissions',
  path: '/Permissions',
  getParentRoute: () => AdminAccessRoute,
} as any)
const AdminAccessMatrixRoute = AdminAccessMatrixRouteImport.update({
  id: '/Matrix',
  path: '/Matrix',
  getParentRoute: () => AdminAccessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/discovery': typeof AdminDiscoveryRouteWithChildren
  '/admin/firefighter': typeof AdminFirefighterRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/ontology': typeof AdminOntologyRouteWithChildren
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/access/Matrix': typeof AdminAccessMatrixRoute
  '/admin/access/Permissions': typeof AdminAccessPermissionsRoute
  '/admin/access/Roles': typeof AdminAccessRolesRoute
  '/admin/access/explorer': typeof AdminAccessExplorerRoute
  '/admin/access/impact': typeof AdminAccessImpactRoute
  '/admin/access/policies': typeof AdminAccessPoliciesRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/admin/ontology/Classes': typeof AdminOntologyClassesRoute
  '/admin/ontology/Graph': typeof AdminOntologyGraphRoute
  '/admin/ontology/Relationships': typeof AdminOntologyRelationshipsRoute
  '/admin/ontology/contexts': typeof AdminOntologyContextsRoute
  '/admin/ontology/designer': typeof AdminOntologyDesignerRoute
  '/admin/ontology/versions': typeof AdminOntologyVersionsRoute
  '/admin/roles/delegation': typeof AdminRolesDelegationRoute
  '/admin/roles/designer': typeof AdminRolesDesignerRoute
  '/admin/roles/manager': typeof AdminRolesManagerRoute
  '/admin/discovery/': typeof AdminDiscoveryIndexRoute
  '/admin/ontology/': typeof AdminOntologyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/firefighter': typeof AdminFirefighterRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/admin': typeof AdminIndexRoute
  '/admin/access/Matrix': typeof AdminAccessMatrixRoute
  '/admin/access/Permissions': typeof AdminAccessPermissionsRoute
  '/admin/access/Roles': typeof AdminAccessRolesRoute
  '/admin/access/explorer': typeof AdminAccessExplorerRoute
  '/admin/access/impact': typeof AdminAccessImpactRoute
  '/admin/access/policies': typeof AdminAccessPoliciesRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/admin/ontology/Classes': typeof AdminOntologyClassesRoute
  '/admin/ontology/Graph': typeof AdminOntologyGraphRoute
  '/admin/ontology/Relationships': typeof AdminOntologyRelationshipsRoute
  '/admin/ontology/contexts': typeof AdminOntologyContextsRoute
  '/admin/ontology/designer': typeof AdminOntologyDesignerRoute
  '/admin/ontology/versions': typeof AdminOntologyVersionsRoute
  '/admin/roles/delegation': typeof AdminRolesDelegationRoute
  '/admin/roles/designer': typeof AdminRolesDesignerRoute
  '/admin/roles/manager': typeof AdminRolesManagerRoute
  '/admin/discovery': typeof AdminDiscoveryIndexRoute
  '/admin/ontology': typeof AdminOntologyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/api-management': typeof ApiManagementRoute
  '/debug': typeof DebugRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/admin/abac': typeof AdminAbacRoute
  '/admin/access': typeof AdminAccessRouteWithChildren
  '/admin/ai': typeof AdminAiRoute
  '/admin/discovery': typeof AdminDiscoveryRouteWithChildren
  '/admin/firefighter': typeof AdminFirefighterRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/ontology': typeof AdminOntologyRouteWithChildren
  '/admin/rate-limits': typeof AdminRateLimitsRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/stats/sessions': typeof StatsSessionsRoute
  '/stats/system': typeof StatsSystemRoute
  '/stats/users': typeof StatsUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/access/Matrix': typeof AdminAccessMatrixRoute
  '/admin/access/Permissions': typeof AdminAccessPermissionsRoute
  '/admin/access/Roles': typeof AdminAccessRolesRoute
  '/admin/access/explorer': typeof AdminAccessExplorerRoute
  '/admin/access/impact': typeof AdminAccessImpactRoute
  '/admin/access/policies': typeof AdminAccessPoliciesRoute
  '/admin/discovery/$serviceId': typeof AdminDiscoveryServiceIdRoute
  '/admin/ontology/Classes': typeof AdminOntologyClassesRoute
  '/admin/ontology/Graph': typeof AdminOntologyGraphRoute
  '/admin/ontology/Relationships': typeof AdminOntologyRelationshipsRoute
  '/admin/ontology/contexts': typeof AdminOntologyContextsRoute
  '/admin/ontology/designer': typeof AdminOntologyDesignerRoute
  '/admin/ontology/versions': typeof AdminOntologyVersionsRoute
  '/admin/roles/delegation': typeof AdminRolesDelegationRoute
  '/admin/roles/designer': typeof AdminRolesDesignerRoute
  '/admin/roles/manager': typeof AdminRolesManagerRoute
  '/admin/discovery/': typeof AdminDiscoveryIndexRoute
  '/admin/ontology/': typeof AdminOntologyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-management'
    | '/debug'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/access'
    | '/admin/ai'
    | '/admin/discovery'
    | '/admin/firefighter'
    | '/admin/navigation'
    | '/admin/new'
    | '/admin/ontology'
    | '/admin/rate-limits'
    | '/admin/schedules'
    | '/admin/sessions'
    | '/admin/users'
    | '/reset-password/$token'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/admin/'
    | '/admin/access/Matrix'
    | '/admin/access/Permissions'
    | '/admin/access/Roles'
    | '/admin/access/explorer'
    | '/admin/access/impact'
    | '/admin/access/policies'
    | '/admin/discovery/$serviceId'
    | '/admin/ontology/Classes'
    | '/admin/ontology/Graph'
    | '/admin/ontology/Relationships'
    | '/admin/ontology/contexts'
    | '/admin/ontology/designer'
    | '/admin/ontology/versions'
    | '/admin/roles/delegation'
    | '/admin/roles/designer'
    | '/admin/roles/manager'
    | '/admin/discovery/'
    | '/admin/ontology/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-management'
    | '/debug'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/access'
    | '/admin/ai'
    | '/admin/firefighter'
    | '/admin/navigation'
    | '/admin/new'
    | '/admin/rate-limits'
    | '/admin/schedules'
    | '/admin/sessions'
    | '/admin/users'
    | '/reset-password/$token'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/admin'
    | '/admin/access/Matrix'
    | '/admin/access/Permissions'
    | '/admin/access/Roles'
    | '/admin/access/explorer'
    | '/admin/access/impact'
    | '/admin/access/policies'
    | '/admin/discovery/$serviceId'
    | '/admin/ontology/Classes'
    | '/admin/ontology/Graph'
    | '/admin/ontology/Relationships'
    | '/admin/ontology/contexts'
    | '/admin/ontology/designer'
    | '/admin/ontology/versions'
    | '/admin/roles/delegation'
    | '/admin/roles/designer'
    | '/admin/roles/manager'
    | '/admin/discovery'
    | '/admin/ontology'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-management'
    | '/debug'
    | '/forgot-password'
    | '/login'
    | '/logs'
    | '/profile'
    | '/register'
    | '/reports'
    | '/admin/abac'
    | '/admin/access'
    | '/admin/ai'
    | '/admin/discovery'
    | '/admin/firefighter'
    | '/admin/navigation'
    | '/admin/new'
    | '/admin/ontology'
    | '/admin/rate-limits'
    | '/admin/schedules'
    | '/admin/sessions'
    | '/admin/users'
    | '/reset-password/$token'
    | '/stats/sessions'
    | '/stats/system'
    | '/stats/users'
    | '/admin/'
    | '/admin/access/Matrix'
    | '/admin/access/Permissions'
    | '/admin/access/Roles'
    | '/admin/access/explorer'
    | '/admin/access/impact'
    | '/admin/access/policies'
    | '/admin/discovery/$serviceId'
    | '/admin/ontology/Classes'
    | '/admin/ontology/Graph'
    | '/admin/ontology/Relationships'
    | '/admin/ontology/contexts'
    | '/admin/ontology/designer'
    | '/admin/ontology/versions'
    | '/admin/roles/delegation'
    | '/admin/roles/designer'
    | '/admin/roles/manager'
    | '/admin/discovery/'
    | '/admin/ontology/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ApiManagementRoute: typeof ApiManagementRoute
  DebugRoute: typeof DebugRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  StatsSessionsRoute: typeof StatsSessionsRoute
  StatsSystemRoute: typeof StatsSystemRoute
  StatsUsersRoute: typeof StatsUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-management': {
      id: '/api-management'
      path: '/api-management'
      fullPath: '/api-management'
      preLoaderRoute: typeof ApiManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stats/users': {
      id: '/stats/users'
      path: '/stats/users'
      fullPath: '/stats/users'
      preLoaderRoute: typeof StatsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/system': {
      id: '/stats/system'
      path: '/stats/system'
      fullPath: '/stats/system'
      preLoaderRoute: typeof StatsSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/sessions': {
      id: '/stats/sessions'
      path: '/stats/sessions'
      fullPath: '/stats/sessions'
      preLoaderRoute: typeof StatsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rate-limits': {
      id: '/admin/rate-limits'
      path: '/rate-limits'
      fullPath: '/admin/rate-limits'
      preLoaderRoute: typeof AdminRateLimitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ontology': {
      id: '/admin/ontology'
      path: '/ontology'
      fullPath: '/admin/ontology'
      preLoaderRoute: typeof AdminOntologyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firefighter': {
      id: '/admin/firefighter'
      path: '/firefighter'
      fullPath: '/admin/firefighter'
      preLoaderRoute: typeof AdminFirefighterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discovery': {
      id: '/admin/discovery'
      path: '/discovery'
      fullPath: '/admin/discovery'
      preLoaderRoute: typeof AdminDiscoveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/access': {
      id: '/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AdminAccessRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/abac': {
      id: '/admin/abac'
      path: '/abac'
      fullPath: '/admin/abac'
      preLoaderRoute: typeof AdminAbacRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ontology/': {
      id: '/admin/ontology/'
      path: '/'
      fullPath: '/admin/ontology/'
      preLoaderRoute: typeof AdminOntologyIndexRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/discovery/': {
      id: '/admin/discovery/'
      path: '/'
      fullPath: '/admin/discovery/'
      preLoaderRoute: typeof AdminDiscoveryIndexRouteImport
      parentRoute: typeof AdminDiscoveryRoute
    }
    '/admin/roles/manager': {
      id: '/admin/roles/manager'
      path: '/roles/manager'
      fullPath: '/admin/roles/manager'
      preLoaderRoute: typeof AdminRolesManagerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/designer': {
      id: '/admin/roles/designer'
      path: '/roles/designer'
      fullPath: '/admin/roles/designer'
      preLoaderRoute: typeof AdminRolesDesignerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles/delegation': {
      id: '/admin/roles/delegation'
      path: '/roles/delegation'
      fullPath: '/admin/roles/delegation'
      preLoaderRoute: typeof AdminRolesDelegationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ontology/versions': {
      id: '/admin/ontology/versions'
      path: '/versions'
      fullPath: '/admin/ontology/versions'
      preLoaderRoute: typeof AdminOntologyVersionsRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/ontology/designer': {
      id: '/admin/ontology/designer'
      path: '/designer'
      fullPath: '/admin/ontology/designer'
      preLoaderRoute: typeof AdminOntologyDesignerRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/ontology/contexts': {
      id: '/admin/ontology/contexts'
      path: '/contexts'
      fullPath: '/admin/ontology/contexts'
      preLoaderRoute: typeof AdminOntologyContextsRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/ontology/Relationships': {
      id: '/admin/ontology/Relationships'
      path: '/Relationships'
      fullPath: '/admin/ontology/Relationships'
      preLoaderRoute: typeof AdminOntologyRelationshipsRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/ontology/Graph': {
      id: '/admin/ontology/Graph'
      path: '/Graph'
      fullPath: '/admin/ontology/Graph'
      preLoaderRoute: typeof AdminOntologyGraphRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/ontology/Classes': {
      id: '/admin/ontology/Classes'
      path: '/Classes'
      fullPath: '/admin/ontology/Classes'
      preLoaderRoute: typeof AdminOntologyClassesRouteImport
      parentRoute: typeof AdminOntologyRoute
    }
    '/admin/discovery/$serviceId': {
      id: '/admin/discovery/$serviceId'
      path: '/$serviceId'
      fullPath: '/admin/discovery/$serviceId'
      preLoaderRoute: typeof AdminDiscoveryServiceIdRouteImport
      parentRoute: typeof AdminDiscoveryRoute
    }
    '/admin/access/policies': {
      id: '/admin/access/policies'
      path: '/policies'
      fullPath: '/admin/access/policies'
      preLoaderRoute: typeof AdminAccessPoliciesRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/impact': {
      id: '/admin/access/impact'
      path: '/impact'
      fullPath: '/admin/access/impact'
      preLoaderRoute: typeof AdminAccessImpactRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/explorer': {
      id: '/admin/access/explorer'
      path: '/explorer'
      fullPath: '/admin/access/explorer'
      preLoaderRoute: typeof AdminAccessExplorerRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/Roles': {
      id: '/admin/access/Roles'
      path: '/Roles'
      fullPath: '/admin/access/Roles'
      preLoaderRoute: typeof AdminAccessRolesRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/Permissions': {
      id: '/admin/access/Permissions'
      path: '/Permissions'
      fullPath: '/admin/access/Permissions'
      preLoaderRoute: typeof AdminAccessPermissionsRouteImport
      parentRoute: typeof AdminAccessRoute
    }
    '/admin/access/Matrix': {
      id: '/admin/access/Matrix'
      path: '/Matrix'
      fullPath: '/admin/access/Matrix'
      preLoaderRoute: typeof AdminAccessMatrixRouteImport
      parentRoute: typeof AdminAccessRoute
    }
  }
}

interface AdminAccessRouteChildren {
  AdminAccessMatrixRoute: typeof AdminAccessMatrixRoute
  AdminAccessPermissionsRoute: typeof AdminAccessPermissionsRoute
  AdminAccessRolesRoute: typeof AdminAccessRolesRoute
  AdminAccessExplorerRoute: typeof AdminAccessExplorerRoute
  AdminAccessImpactRoute: typeof AdminAccessImpactRoute
  AdminAccessPoliciesRoute: typeof AdminAccessPoliciesRoute
}

const AdminAccessRouteChildren: AdminAccessRouteChildren = {
  AdminAccessMatrixRoute: AdminAccessMatrixRoute,
  AdminAccessPermissionsRoute: AdminAccessPermissionsRoute,
  AdminAccessRolesRoute: AdminAccessRolesRoute,
  AdminAccessExplorerRoute: AdminAccessExplorerRoute,
  AdminAccessImpactRoute: AdminAccessImpactRoute,
  AdminAccessPoliciesRoute: AdminAccessPoliciesRoute,
}

const AdminAccessRouteWithChildren = AdminAccessRoute._addFileChildren(
  AdminAccessRouteChildren,
)

interface AdminDiscoveryRouteChildren {
  AdminDiscoveryServiceIdRoute: typeof AdminDiscoveryServiceIdRoute
  AdminDiscoveryIndexRoute: typeof AdminDiscoveryIndexRoute
}

const AdminDiscoveryRouteChildren: AdminDiscoveryRouteChildren = {
  AdminDiscoveryServiceIdRoute: AdminDiscoveryServiceIdRoute,
  AdminDiscoveryIndexRoute: AdminDiscoveryIndexRoute,
}

const AdminDiscoveryRouteWithChildren = AdminDiscoveryRoute._addFileChildren(
  AdminDiscoveryRouteChildren,
)

interface AdminOntologyRouteChildren {
  AdminOntologyClassesRoute: typeof AdminOntologyClassesRoute
  AdminOntologyGraphRoute: typeof AdminOntologyGraphRoute
  AdminOntologyRelationshipsRoute: typeof AdminOntologyRelationshipsRoute
  AdminOntologyContextsRoute: typeof AdminOntologyContextsRoute
  AdminOntologyDesignerRoute: typeof AdminOntologyDesignerRoute
  AdminOntologyVersionsRoute: typeof AdminOntologyVersionsRoute
  AdminOntologyIndexRoute: typeof AdminOntologyIndexRoute
}

const AdminOntologyRouteChildren: AdminOntologyRouteChildren = {
  AdminOntologyClassesRoute: AdminOntologyClassesRoute,
  AdminOntologyGraphRoute: AdminOntologyGraphRoute,
  AdminOntologyRelationshipsRoute: AdminOntologyRelationshipsRoute,
  AdminOntologyContextsRoute: AdminOntologyContextsRoute,
  AdminOntologyDesignerRoute: AdminOntologyDesignerRoute,
  AdminOntologyVersionsRoute: AdminOntologyVersionsRoute,
  AdminOntologyIndexRoute: AdminOntologyIndexRoute,
}

const AdminOntologyRouteWithChildren = AdminOntologyRoute._addFileChildren(
  AdminOntologyRouteChildren,
)

interface AdminRouteChildren {
  AdminAbacRoute: typeof AdminAbacRoute
  AdminAccessRoute: typeof AdminAccessRouteWithChildren
  AdminAiRoute: typeof AdminAiRoute
  AdminDiscoveryRoute: typeof AdminDiscoveryRouteWithChildren
  AdminFirefighterRoute: typeof AdminFirefighterRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminOntologyRoute: typeof AdminOntologyRouteWithChildren
  AdminRateLimitsRoute: typeof AdminRateLimitsRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRolesDelegationRoute: typeof AdminRolesDelegationRoute
  AdminRolesDesignerRoute: typeof AdminRolesDesignerRoute
  AdminRolesManagerRoute: typeof AdminRolesManagerRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAbacRoute: AdminAbacRoute,
  AdminAccessRoute: AdminAccessRouteWithChildren,
  AdminAiRoute: AdminAiRoute,
  AdminDiscoveryRoute: AdminDiscoveryRouteWithChildren,
  AdminFirefighterRoute: AdminFirefighterRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminNewRoute: AdminNewRoute,
  AdminOntologyRoute: AdminOntologyRouteWithChildren,
  AdminRateLimitsRoute: AdminRateLimitsRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRolesDelegationRoute: AdminRolesDelegationRoute,
  AdminRolesDesignerRoute: AdminRolesDesignerRoute,
  AdminRolesManagerRoute: AdminRolesManagerRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ApiManagementRoute: ApiManagementRoute,
  DebugRoute: DebugRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  StatsSessionsRoute: StatsSessionsRoute,
  StatsSystemRoute: StatsSystemRoute,
  StatsUsersRoute: StatsUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
